name: auth_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  google_sign_in: ^5.2.4
  meta: ^1.7.0
  very_good_analysis: ^2.4.0
  cache:
    path: ../cache

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0